project:
  type: website

website:
  title: "Alex Kuhn"
  search: false
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: minty 
    css: styles.css

